### ISSUE TITLE
Support specific apps connector on xDai network

### ISSUE THREAD

**Issue by 0xGabi** [aragon/connect#141]
This issue is to keep track of:

- [x] Deploy Voting and Tokens app subgraphs to xDai.

- [x] Update app connectors configuration to support xDai as default.

**Comment by bpierre** [comment]
@0xGabi should we close this issue now that https://github.com/aragon/connect/pull/157 is merged?

**Comment by 0xGabi** [comment]
Actually, we might want to deploy them from the official Aragon account, but I didn't have permission. I deploy them on my own account for now.

**Comment by 0xGabi** [comment]
The subgraphs were deployed from the official Aragon account now.
