### ISSUE TITLE
<BUG> Can't resolve '@aragon/connect-react'

### ISSUE THREAD

**Issue by vlzhr** [aragon/connect#159]
"Can't resolve '@aragon/connect-react'" while running connect-react-intro

**Comment by bpierre** [comment]
Hi @vlzhr, did you run `yarn install`?

**Comment by vlzhr** [comment]
Yep, I downloaded full "connect" folder. Then ran `yarn install`. Modules seem installed in the /node_modules folder

**Comment by bpierre** [comment]
I was trying from a clean fresh clone, and while I didn’t encounter the issue you describe, there seem to be a problem with the webpack plugin. Could you try with [the `connect-react-intro-fix` branch](https://github.com/aragon/connect/pull/160) and let me know?

**Comment by bpierre** [comment]
@vlzhr I merged the PR, the issue should be fixed now. Please try again and let us know if you encounter any issue!
