### ISSUE TITLE
API refactor: Update types definition

### ISSUE THREAD

**Issue by 0xGabi** [aragon/connect#212]
Update the types to those described on #132

**Comment by steffclearteam** [comment]
@nivida This issue has no description and no assignees currently. Should it be moved to another column for lower priority issues?

**Comment by nivida** [comment]
@steffclearteam As I have seen is the description existing because it is a sub-task of #132. But now after having a quick look at PR #223 is it clear see that those changes were included already in PR #256. Thanks, @0xGabi for referencing this already merged PR in yours.
